fs/yaffs2: fix build warnings in yaffs_vfs.c when running make allyesconfig
When building linux yocto with allyesconfig, some build warnings are found:

fs/yaffs2/yaffs_vfs.c:1292:15: error: no previous prototype for
‘yaffs_get_inode’ [-Werror=missing-prototypes]
 1292 | struct inode *yaffs_get_inode(struct super_block *sb, int mode,
      int dev,
      |               ^~~~~~~~~~~~~~~
fs/yaffs2/yaffs_vfs.c: In function ‘yaffs_iterate’:
fs/yaffs2/yaffs_vfs.c:1841:13: error: unused variable ‘i_version’
[-Werror=unused-variable]
 1841 |         u64 i_version;
      |             ^~~~~~~~~
fs/yaffs2/yaffs_vfs.c: At top level:
fs/yaffs2/yaffs_vfs.c:2441:16: error: no previous prototype for
‘yaffs2_get_parent’ [-Werror=missing-prototypes]
 2441 | struct dentry *yaffs2_get_parent(struct dentry *dentry)
      |                ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Inspect the code that the two functions yaffs_get_inode() and
yaffs2_get_parent() are only used in the current file, i_version is not
used in the function yaffs_iterate(). So add the static modifier to the
two functions and remove the variable i_version.

Signed-off-by: Bin Lan <bin.lan.cn@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>